### ISSUE TITLE
How did you manage to implement the functionality of adding purchased tours on the user page?

### ISSUE THREAD

**Issue by haosmos** [hungdao-testing/natours_api#27]
Hello! 😃

I stumbled across your project by accident - a very well organized project! 👍 Great job! 💪

I was looking for projects where the functionality of displaying the purchased tour after the checkout session was completed was successfully implemented - for some reason I can't implement it. Although the code is exactly the same as in the original Jonas repository and the same as yours.

Maybe you can suggest what could be the problem? Purchased tours are displayed in strapi, but the webhook does not work:

![chrome_g9MRYTzm23](https://user-images.githubusercontent.com/30666874/179418444-3b85ee40-9588-4fbb-8422-acbd9af7796e.png)

user not found:

![chrome_FYe5SADriU](https://user-images.githubusercontent.com/30666874/179418421-046ee705-7548-4372-a091-cbff5ccb57dc.png)

the error comes from here:

![GWSL_vcxsrv_R6HfuGC7Hx](https://user-images.githubusercontent.com/30666874/179419835-79ec0bf1-74cf-41fd-8c1c-f3c479593236.png)

tell me, please, what could be the problem?

The redirect to the user's tours page works, but for some reason it is impossible to find the user, judging by the error.
tell me, please, what could be the problem? Maybe you have encountered such a problem?

in the `app.js` file I use `express.raw({type: application/json})` as I need to use "raw" data:

![GWSL_vcxsrv_ACGX5Mka90](https://user-images.githubusercontent.com/30666874/179419578-587d3705-5882-4f27-9a0d-d789240258f7.png)

from my perspective, my code is exactly the same as yours, except you used typescript but the code is basically the same i think. - here is the code of the `bookingController.js` file:

![GWSL_vcxsrv_oRl7N3ARF8](https://user-images.githubusercontent.com/30666874/179419586-f8fd4f22-0c43-419e-8268-268f7233d6e7.png)

and here is the rest of the code:

![GWSL_vcxsrv_tDUNtbmgnp](https://user-images.githubusercontent.com/30666874/179419614-1ba7e974-9cd3-496e-b382-dbddaab1c964.png)

I also checked the environment variables several times - they are correct and I specified them in the heroku settings

I have been trying to solve this problem for the third day and I can not understand why my code does not work ((

here is what i get:

https://user-images.githubusercontent.com/30666874/179420275-7f293200-f40d-4c41-a988-332c1309f234.mp4

**Comment by hungdao-testing** [comment]
@haosmos : thanks for visiting my repo, 

At the first look, I see the lines (66->68) you find user by statement below
```ts
let user = (await User.findOne({ email: session.customer_email})).id  // means find user and return `id `(string) not whole of user object
```
please remove the `id` and try it again.

![image](https://user-images.githubusercontent.com/30666874/179419835-79ec0bf1-74cf-41fd-8c1c-f3c479593236.png)

**Comment by haosmos** [comment]
> @haosmos : thanks for visiting my repo,
> 
> At the first look, I see the lines (66->68) you find user by statement below
> 
> ```ts
> let user = (await User.findOne({ email: session.customer_email})).id  // means find user and return `id `(string) not whole of user object
> ```
> 
> please remove the `id` and try it again.
> 
> ![image](https://user-images.githubusercontent.com/30666874/179419835-79ec0bf1-74cf-41fd-8c1c-f3c479593236.png)

works! Thanks a lot! 👍
